import dotenv
import os
from pybit.unified_trading import HTTP

dotenv.load_dotenv()

TEST = os.getenv('TEST')


API_KEY = os.getenv('API_KEY')
API_NAME = os.getenv('API_NAME')
API_SECRET = os.getenv('API_SECRET')


POSTGRES_LOGIN = os.getenv('POSTGRES_LOGIN') if not TEST else os.getenv('POSTGRES_TEST_LOGIN')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD') if not TEST else os.getenv('POSTGRES_TEST_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRES_HOST') if not TEST else os.getenv('POSTGRES_TEST_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT') if not TEST else os.getenv('POSTGRES_TEST_PORT')
POSTGRES_NAME = os.getenv('POSTGRES_NAME') if not TEST else os.getenv('POSTGRES_TEST_NAME')
POSTGRES_ADMIN = os.getenv('POSTGRES_ADMIN') if not TEST else os.getenv('POSTGRES_TEST_ADMIN')
POSTGRES_ADMIN_PASSWORD = os.getenv('POSTGRES_ADMIN_PASSWORD') if not TEST else os.getenv('POSTGRES_TEST_ADMIN_PASSWORD')

# PERCENT_TO_KEEP_IN_CRYPTOCURRENCY_AFTER_ITERATION = 50
# PERCENT_PRICE_INCREASE = 1
# PERCENT_STEP_PER_ORDER = 0.6
# MAX_ORDER_COUNT = 10
START_BALANCE = 500
# DELAY_BETWEEN_REQUESTS = 120
# PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE = 0.25
# MAX_PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE = 1



BASE_URL = 'https://api.bybit.com'
# TRADE_PAIR = 'BTCUSDT'
# COMMISSION = 0.2
# REVENUE_WITHOUT_COMMISION = PERCENT_PRICE_INCREASE - COMMISSION
# PERCENT_REVENUE_USD_PER_ROUND = (100 - PERCENT_TO_KEEP_IN_CRYPTOCURRENCY_AFTER_ITERATION) * REVENUE_WITHOUT_COMMISION / 100
# PERCENT_REVENUE_BTC_PER_ROUND = PERCENT_TO_KEEP_IN_CRYPTOCURRENCY_AFTER_ITERATION * REVENUE_WITHOUT_COMMISION / 100



CLIENT = HTTP(
    testnet=False,
    api_key=API_KEY,
    api_secret=API_SECRET,
    # recv_window=100000,
)
