import dotenv
import os
from pybit.unified_trading import HTTP

dotenv.load_dotenv()


API_KEY = os.getenv('API_KEY')
API_NAME = os.getenv('API_NAME')
API_SECRET = os.getenv('API_SECRET')


POSTGRES_LOGIN = os.getenv('POSTGRES_LOGIN')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
POSTGRES_NAME = os.getenv('POSTGRES_NAME')

BASE_URL = 'https://api.bybit.com'

# BASE TRADE SETTINGS
START_BALANCE = os.getenv('START_BALANCE')
DELAY_BETWEEN_REQUESTS = os.getenv('DELAY_BETWEEN_REQUESTS')
PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE = os.getenv('PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE')
MAX_PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE = os.getenv('MAX_PERCENT_BETWEEN_FIRST_ORDER_AND_CURRENT_PRICE')
PERCENT_TO_KEEP_IN_CRYPTOCURRENCY_AFTER_ITERATION = os.getenv('PERCENT_TO_KEEP_IN_CRYPTOCURRENCY_AFTER_ITERATION')
REVENUE_PERCENT = os.getenv('REVENUE_PERCENT')
PERCENT_STEP_PER_ORDER = os.getenv('PERCENT_STEP_PER_ORDER')
MAX_ORDER_COUNT = os.getenv('MAX_ORDER_COUNT')
TRADE_PAIR = os.getenv('TRADE_PAIR')

CLIENT = HTTP(
    testnet=False,
    api_key=API_KEY,
    api_secret=API_SECRET,
    # recv_window=100000,
)
