"""trade settings

Revision ID: bybitbot0006
Revises: bybitbot0005
Create Date: 2025-02-09 16:08:17.522122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bybitbot0006'
down_revision: Union[str, None] = 'bybitbot0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue_percent', sa.Float(), server_default='0', nullable=False),
    sa.Column('percent_of_revenue_to_keep_in_crypto', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('percent_step_per_order', sa.Float(), nullable=False),
    sa.Column('max_order_count', sa.SmallInteger(), nullable=False),
    sa.Column('delay_between_requests_in_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('percent_between_first_order_and_current_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('max_percent_between_first_order_and_current_price', sa.Float(), nullable=False),
    sa.Column('trade_pair', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_settings')
    # ### end Alembic commands ###
