"""add trade pair to revenue

Revision ID: bybitbot0004
Revises: bybitbot0003
Create Date: 2025-01-19 12:29:54.484281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bybitbot0004'
down_revision: Union[str, None] = 'bybitbot0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue', sa.Column('trade_pair', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenue', 'trade_pair')
    # ### end Alembic commands ###
