"""orders

Revision ID: bybitbot0002
Revises: bybitbot0001
Create Date: 2024-12-15 22:37:46.306193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bybitbot0002'
down_revision: Union[str, None] = 'bybitbot0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('buy', 'sell', name='order_type_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_order_link_id', sa.String(length=64), nullable=True),
    sa.Column('status', postgresql.ENUM('placed', 'cancelled', 'error', 'filled', 'completed', name='order_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_trade_pair', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=64), server_default='Limit', nullable=False),
    sa.Column('order_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('order_quantity', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('order_executed_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.execute('DROP TYPE order_status_enum')
    op.execute('DROP TYPE order_type_enum')
    # ### end Alembic commands ###
