"""revenue

Revision ID: bybitbot0003
Revises: bybitbot0002
Create Date: 2025-01-06 16:48:26.764491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bybitbot0003'
down_revision: Union[str, None] = 'bybitbot0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filled_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_orders', sa.Integer(), nullable=False),
    sa.Column('revenue_usd', sa.DECIMAL(precision=10, scale=6), server_default='0', nullable=True),
    sa.Column('revenue_btc', sa.DECIMAL(precision=10, scale=6), server_default='0', nullable=True),
    sa.Column('current_avg_price', sa.DECIMAL(precision=10, scale=2), server_default='0', nullable=True),
    sa.Column('current_quantity', sa.DECIMAL(precision=10, scale=6), server_default='0', nullable=True),
    sa.Column('finish', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('revenue_id', sa.Integer(), nullable=False))

    op.create_foreign_key('fk_orders_revenue_id', 'orders', 'revenue', ['revenue_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_revenue_id', 'orders', type_='foreignkey')

    op.drop_column('orders', 'revenue_id')

    op.drop_table('revenue')
    # ### end Alembic commands ###
