"""empty message

Revision ID: bybitbot0008
Revises: bybitbot0007
Create Date: 2025-03-03 00:33:26.069456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bybitbot0008'
down_revision: Union[str, None] = 'bybitbot0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_settings', sa.Column('power', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_settings', 'power')
    # ### end Alembic commands ###
