"""balance

Revision ID: bybitbot0001
Revises: 
Create Date: 2024-12-15 21:26:33.042547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from cfg import START_BALANCE
from infrastructure.stored_procedures.balance.balance_check_rows_limit import sql_register_store_proc_balance_check_rows_limit, \
    sql_drop_store_proc_balance_check_rows_limit
from infrastructure.triggers.balance.balance_triggers import sql_register_trigger_balance_before_insert_check_rows_limit, \
    sql_drop_trigger_balance_before_insert_check_rows

# revision identifiers, used by Alembic.
revision: str = 'bybitbot0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('current_sum', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


    op.execute(sql_register_store_proc_balance_check_rows_limit())

    op.execute(sql_register_trigger_balance_before_insert_check_rows_limit())

    op.execute(f"""INSERT INTO balance (current_sum) VALUES ({START_BALANCE})""")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sql_drop_trigger_balance_before_insert_check_rows())

    op.execute(sql_drop_store_proc_balance_check_rows_limit())

    op.drop_table('balance')
    # ### end Alembic commands ###
