"""store_procs, triggers, new order column

Revision ID: bybitbot0005
Revises: bybitbot0004
Create Date: 2025-02-02 11:58:29.031116

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from infrastructure.models.order_models.enums import OrderStatusEnum, OrderTypeEnum

# revision identifiers, used by Alembic.
revision: str = 'bybitbot0005'
down_revision: Union[str, None] = 'bybitbot0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_fact_price', sa.Float(), nullable=True))

    op.execute(f"""
    CREATE OR REPLACE FUNCTION update_revenue_row_after_fill_order()
    RETURNS TRIGGER AS $$
    DECLARE
        new_revenue_usd NUMERIC;
        new_revenue_btc NUMERIC;
    BEGIN
        IF OLD.status != NEW.status AND NEW.type = '{OrderTypeEnum.buy.value}' THEN
            
            IF OLD.status = '{OrderStatusEnum.placed.value}' AND NEW.status = '{OrderStatusEnum.filled.value}' THEN
            
                IF NEW.order_executed_value IS NULL OR NEW.order_quantity IS NULL OR NEW.order_fact_price IS NULL THEN
                    RAISE EXCEPTION 'order_executed_value, order_quantity, order_fact_price ДОЛЖНЫ БЫТЬ ЗАПОЛНЕНЫ';
                END IF;
    
                new_revenue_usd := NEW.order_executed_value * 0.4 / (100 + 0.4);
                new_revenue_btc := NEW.order_quantity * 0.4 / (100 + 0.4);
                
                UPDATE revenue
                SET 
                    filled_orders = filled_orders + 1,
                    revenue_usd = COALESCE(revenue_usd, 0) + new_revenue_usd,
                    revenue_btc = COALESCE(revenue_btc, 0) + new_revenue_btc,
                    current_avg_price = ROUND(((COALESCE(current_avg_price, 0)::NUMERIC * COALESCE(current_quantity, 0) + NEW.order_fact_price * NEW.order_quantity) / NULLIF((COALESCE(current_quantity, 0) + NEW.order_quantity), 0))::NUMERIC, 8),
                    current_quantity = COALESCE(current_quantity, 0) + NEW.order_quantity,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = NEW.revenue_id;
                    
            ELSIF OLD.status = '{OrderStatusEnum.filled.value}' AND NEW.status = '{OrderStatusEnum.placed.value}' THEN
    
                new_revenue_usd := NEW.order_executed_value * 0.4 / (100 + 0.4);
                new_revenue_btc := NEW.order_quantity * 0.4 / (100 + 0.4);
                
                UPDATE revenue
                SET 
                    filled_orders = filled_orders - 1,
                    revenue_usd = revenue_usd - new_revenue_usd,
                    revenue_btc = revenue_btc - new_revenue_btc,
                    current_avg_price = ROUND(((COALESCE(current_avg_price, 0)::NUMERIC * COALESCE(current_quantity, 0) - NEW.order_fact_price * NEW.order_quantity) / NULLIF((COALESCE(current_quantity, 0) - NEW.order_quantity), 0))::NUMERIC, 8),
                    current_quantity = current_quantity - NEW.order_quantity,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = NEW.revenue_id;
    
            END IF;
    
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION before_update_check_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
        IF OLD.updated_at = NEW.updated_at THEN
            NEW.updated_at = CURRENT_TIMESTAMP;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE OR REPLACE TRIGGER before_update_check_updated_at
    BEFORE INSERT ON orders
    FOR EACH ROW
    EXECUTE FUNCTION before_update_check_updated_at();
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER before_update_check_updated_at
    BEFORE INSERT ON revenue
    FOR EACH ROW
    EXECUTE FUNCTION before_update_check_updated_at();
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER after_fill_order_change_revenue_row
    AFTER UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_revenue_row_after_fill_order();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DROP TRIGGER IF EXISTS after_fill_order_change_revenue_row ON orders
    """)
    op.execute("""
    DROP TRIGGER IF EXISTS before_update_check_updated_at ON orders
    """)
    op.execute("""
    DROP TRIGGER IF EXISTS before_update_check_updated_at ON revenue
    """)

    op.execute("""
        DROP FUNCTION IF EXISTS before_update_check_updated_at
    """)
    op.execute("""
        DROP FUNCTION IF EXISTS update_revenue_row_after_fill_order
    """)

    op.drop_column('orders', 'order_fact_price')
    # ### end Alembic commands ###
